# -*- coding: utf-8 -*-
"""spatialdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4NDDwwmu7tHraXVXkI67xsL727gcKi9
"""

pip install folium

import folium
mymap=folium.Map(location=[13.43,77.72],
                 width=950,
                 height=550,
                 zoom_star=12,
                 titles='opentreemap')
mymap

folium.Marker(location=[13.43,77.72],popup='Default popup Marker1',tooltip='Click here to see popup').add_to(mymap)
mymap

import folium
mymap=folium.Map(location=[13.338263,77.101410],
                 width=950,
                 height=550,
                 zoom_star=12,
                 titles='opentreemap')
mymap

folium.Marker(location=[12.295810,76.639381],popup='Default popup Marker1',tooltip='Click here to see popup').add_to(mymap)
mymap

import folium
m = folium.Map(location=[13.43, 77.72], zoom_start=13)
locations = [[12.978889, 77.591667], [13.113889, 77.598333], [13.23, 77.7]]
image_paths = [
    "https://www.godrej-ananda.net.in/images/other/how-bangalore-got-its-name.webp",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ3-by5ZIplq7R0Af7A5NV2aDcoRW0-LasoQbZcR1iEA&s",
    "https://assets-news.housing.com/news/wp-content/uploads/2016/11/23154121/Devanahalli.jpg"
]

for location, image_path in zip(locations, image_paths):
  html = f'<img src="{image_path}" alt="Picture" width="200">'
  folium.Marker(location, popup=html).add_to(m)
m

